### ISSUE TITLE
Create Registration and Login Components

### ISSUE THREAD

**Issue by brightiortsor** [0xlarmideh/pos-sales-app#1]
- [x] Add a register page
- [x] Add a login page
- [x] Both pages should be wrapped around a layout
- [x] The Layout should just have a Logo entered and a few random food svgs arranged randomly at the bottom at the bottom while the main component is rendered in the middle. Refer to image below.

![Screenshot (4)](https://user-images.githubusercontent.com/99312664/227716647-f6319d86-fc0d-4640-87ed-aab653495919.png)

**Comment by 0xlarmideh** [comment]
Working on this.

**Comment by 0xlarmideh** [comment]
We do not need a register page btw, it's a sales POS app. Users will be created on the backend and roles administered.
