### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by brightiortsor** [0xlarmideh/pos-sales-app#6]
- This component should render a list of card components comprising of all available dishes

![Screenshot (8)](https://user-images.githubusercontent.com/99312664/227718700-027de52c-6421-4af0-af22-431ca92d88d2.png)

**Comment by 0xlarmideh** [comment]
Will work on this

**Comment by 0xlarmideh** [comment]
I think we have to create some mock database at some point to mock how this works. Every category will have a nested object that includes all the products, available items, price and all infos. That way we can display at the bottom a mapped view of a category once clicked. Will look into creating that kind of database with sanity.
